### ISSUE TITLE
Macro recorder error capturing 'remove vis by distance' 

### ISSUE THREAD

**Issue by StephanJanosch** [bigdataviewer/SPIM_Registration#12]
The parameter names are messed up. This way there is no way to automate thinning out nuclei

IJ.run("Remove Detections by Distance", "select_xml=/Volumes/wormspim2-1/141009_Cel_OP43/Worm1//OP43_Worm1_1.xml "+
"process_angle=[All angles] "+
"process_illumination=[All illuminations] "+
"process_timepoint=[All Timepoints] "+
"channel_dapi "+
"channel_dapi=nuclei "+
"channel_dapi=thinned-out "+
"channel_dapi=1 "+
"channel_gfp=[[DO NOT thin out this channel]] "+
"channel_gfp=t2 "+
"channel_gfp=2 "+
"channel_dapi_=[Keep Range] "+
"channel_dapi_range_lower_threshold=0 "+
"channel_dapi_range_upper_threshold=10");

**Comment by StephanPreibisch** [comment]
Fixed with commit ef48111fec17a702ac9d65bad3efa1da88558cc6. Learned that macro recording does not support ':' in the label.
