### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by psteinb** [bigdataviewer/SPIM_Registration#13]
hi (me again),

I am still trying to run SPIM_Registration. So, I download a fresh fiji bundle from
http://jenkins.imagej.net/job/Stable-Fiji/lastSuccessfulBuild/artifact/fiji-linux64.tar.gz
just now.
The contained vanilla version of SPIM_Registration works. Yihaw! But I need to work with the plugin, branching and creating pull requests. And that generates the error mentioned below.

```
(Fiji Is Just) ImageJ 2.0.0-rc-26/1.49p; Java 1.6.0_24 [64-bit]; Linux 3.10.0-123.13.2.el7.x86_64; 950MB of 40353MB (2%)
 
java.lang.NullPointerException
	at mpicbg.imglib.interpolation.linear.LinearInterpolator.moveTo(LinearInterpolator.java:306)
	at mpicbg.spim.postprocessing.deconvolution.ExtractPSF.extractPSF(ExtractPSF.java:451)
	at mpicbg.spim.postprocessing.deconvolution.ExtractPSF.extract(ExtractPSF.java:278)
	at mpicbg.spim.fusion.PreDeconvolutionFusionSequential.fuseSPIMImages(PreDeconvolutionFusionSequential.java:555)
	at mpicbg.spim.fusion.FusionControl.fuse(FusionControl.java:80)
	at mpicbg.spim.fusion.FusionControl.fuse(FusionControl.java:23)
	at mpicbg.spim.Reconstruction.processIndividualViewStructure(Reconstruction.java:330)
	at mpicbg.spim.Reconstruction.<init>(Reconstruction.java:44)
	at fiji.plugin.Multi_View_Deconvolution.run(Multi_View_Deconvolution.java:83)
	at ij.IJ.runUserPlugIn(IJ.java:199)
	at ij.IJ.runPlugIn(IJ.java:163)
	at ij.Executer.runCommand(Executer.java:131)
	at ij.Executer.run(Executer.java:64)
	at java.lang.Thread.run(Thread.java:662)
```

As suggested in https://github.com/bigdataviewer/SPIM_Registration/issues/10, I build SPIM_Registration and then copied mpicbg{,_} (1.0.1) and legacy-imglib1 (1.1.2) that it requires from  the ~/.m2 directory into /path/to/fiji/jars. If there are other ways, please let me know. 
I put the input data here for those curious to try it:
https://idisk.mpi-cbg.de/~steinbac/celegans.zip (330 MB)
As the input data works with the vanilla version, I doubt that it is the cause of this. But I provide it for clarity. For completeness, I compiled against 4e3a8f645d213c88177abc92ffcde097b271fcea for all of this.

Is that a bug or user misuse? in the meantime, I'll try to roll back SPIM_Registration to 2.1.3 and use that for experimentation. But as I want to contribute, that is not ideal.

**Comment by ctrueden** [comment]
@psteinb I more reliable option to install a modified plugin is:
```
mvn -Dimagej.app.directory=/Applications/Fiji.app -Ddelete.other.versions=true
```
From the project you are building. This will cause the artifact and its dependencies to be copied into the specified ImageJ installation, removing any other versions. Doing it manually has a higher chance that you will forget to update or add a needed JAR file, especially for projects like `SPIM_Registration` with complex dependency hierarchies.

Regardless, I would not copy stuff out of `~/.m2/repository` in most cases; better to use `mvn dependency:copy-dependencies` to copy the correct versions of needed dependencies into the project's `target/dependencies` folder. You can then copy them again from there, knowing that the JARs you're copying are the right ones.

**Comment by axtimwalde** [comment]
Hi Peter,

thanks for reporting this bug.  I found it and I am working on a fix...

Cheers,
Stephan

**Comment by axtimwalde** [comment]
@psteinb Please test with SPIM_Registration-2.1.5 and legacy-imglib1-1.1.3-DEPRECATED.

**Comment by psteinb** [comment]
using

```
mvn -Dimagej.app.directory=/path/to/Fiji.app -Ddelete.other.versions=true
```
works like a charm! It pushed SPIM_Registration-2.1.7-SNAPSHOT.jar to 
the plugins dir and that one works well. Alright, I'll start next week 
on adding libmultiviewnative as an option to SPIM_Registration and emit 
PR(s).

Best
