### ISSUE TITLE
detection selection broken in registration

### ISSUE THREAD

**Issue by StephanJanosch** [bigdataviewer/SPIM_Registration#20]
there is nuclei detection in ch1, but the selection dialog shows it to me

![screenshot from 2015-04-08 12 09 26](https://cloud.githubusercontent.com/assets/11651596/7043244/7c73d09c-dde8-11e4-8ae9-0ff4c3247d01.png)
![screenshot from 2015-04-08 12 10 03](https://cloud.githubusercontent.com/assets/11651596/7043245/7e7bce8a-dde8-11e4-8d4f-1469ad79d428.png)
![screenshot from 2015-04-08 12 10 28](https://cloud.githubusercontent.com/assets/11651596/7043248/80fce176-dde8-11e4-858a-daf755d08a7a.png)

**Comment by StephanPreibisch** [comment]
Also fixed with this commit https://github.com/bigdataviewer/SPIM_Registration/commit/fd249a909dbe6943ec895ae97cc94fddeedacb28

**Comment by StephanPreibisch** [comment]
By the way, right click and activate the Interest Point Explorer and Registration Explorer will give way more details ...
