### ISSUE TITLE
PSF extraction crashes

### ISSUE THREAD

**Issue by StephanJanosch** [bigdataviewer/SPIM_Registration#21]
Log:
```
Extracting PSF for viewsetup 5 using label 'beads' (235 corresponding detections available)
PSF size: (25, 25, 21)
Fusing view 2 of 3
(Wed Apr 08 15:20:45 CEST 2015): Reserving memory for fused & weight image.
Wed Apr 08 15:20:51 CEST 2015: Opening '/home/janosch/Documents/worm7/././Track2(2).czi' [1920x1920x266 ch=0 tp=0 type=uint16 image=ArrayImg<FloatType>]
Extracting PSF for viewsetup 6 using label 'beads' (204 corresponding detections available)
PSF size: (25, 25, 21)
Fusing view 3 of 3
(Wed Apr 08 15:21:33 CEST 2015): Reserving memory for fused & weight image.
Wed Apr 08 15:21:34 CEST 2015: Opening '/home/janosch/Documents/worm7/././Track2(3).czi' [1920x1920x323 ch=0 tp=0 type=uint16 image=ArrayImg<FloatType>]
Extracting PSF for viewsetup 7 using label 'beads' (195 corresponding detections available)
PSF size: (25, 25, 21)
Minimal number of overlapping views: 3, using 3
Average number of overlapping views: 3.9671895845906646, using 3.9671895845906646
Type of iteration: OPTIMIZATION_I
Number iterations: 5
OSEM speedup: 3.0
Using blocks: true
Block size: (256, 256, 256)
Using CUDA: true
Blending border: 12x12x4
Blending range: 25x25x25
PSF size (extracting): 25x25x21
Channel 2 extracts from label 'beads'. 
ImgLib container (deconvolved): ArrayImgFactory
Using Tikhonov regularization (lambda = 0.0060)
maxSize: (57, 93, 93)
```

```
Exception in thread "Thread-21" java.lang.NullPointerException
	at spim.process.fusion.deconvolution.ExtractPSF.computeAverageTransformedPSF(ExtractPSF.java:157)
	at spim.process.fusion.deconvolution.EfficientBayesianBased.displayParametersAndPSFs(EfficientBayesianBased.java:447)
	at spim.process.fusion.deconvolution.EfficientBayesianBased.fuseData(EfficientBayesianBased.java:191)
	at spim.fiji.plugin.Image_Fusion.fuse(Image_Fusion.java:157)
	at spim.fiji.plugin.Image_Fusion.fuse(Image_Fusion.java:82)
	at spim.fiji.spimdata.explorer.popup.FusionPopup$MyActionListener$1.run(FusionPopup.java:55)
	at java.lang.Thread.run(Thread.java:662)

```
![screenshot from 2015-04-08 15 16 34](https://cloud.githubusercontent.com/assets/11651596/7046032/5f1b15f8-de03-11e4-961e-2107a174baa2.png)
![screenshot from 2015-04-08 15 17 40](https://cloud.githubusercontent.com/assets/11651596/7046037/62cf74f0-de03-11e4-8238-3999b765a63a.png)
![screenshot from 2015-04-08 15 17 52](https://cloud.githubusercontent.com/assets/11651596/7046040/679d0cae-de03-11e4-88eb-cd033491c965.png)
![screenshot from 2015-04-08 15 18 10](https://cloud.githubusercontent.com/assets/11651596/7046042/6a11fa1c-de03-11e4-9777-f379157e6e96.png)
![screenshot from 2015-04-08 15 18 24](https://cloud.githubusercontent.com/assets/11651596/7046043/6bd6b4fa-de03-11e4-819f-c2e37a66fbf3.png)
![screenshot from 2015-04-08 15 18 33](https://cloud.githubusercontent.com/assets/11651596/7046044/6d81a166-de03-11e4-8a48-dcb4e3cba475.png)
![screenshot from 2015-04-08 15 18 41](https://cloud.githubusercontent.com/assets/11651596/7046046/6f454822-de03-11e4-91ee-28660e1583ab.png)
![screenshot from 2015-04-08 15 18 54](https://cloud.githubusercontent.com/assets/11651596/7046047/70f7427e-de03-11e4-8205-9e8af4c9a758.png)

**Comment by StephanPreibisch** [comment]
Fixed with commit https://github.com/bigdataviewer/SPIM_Registration/commit/35a17f4323da8c6298bc99497209763ff63b2d13
