### ISSUE TITLE
Reorientation is missing registrations

### ISSUE THREAD

**Issue by StephanJanosch** [bigdataviewer/SPIM_Registration#22]
Dataset 2 channels. Both have beads, one has nuclei. All registered. 

If I want to fuse channel GFP with the reorientation of nuclei of channel DAPI, the reorientation dialog is missing the registrations of the DAPI channel.

A little extra test shows, that the reorientation only knows about the registration of the selected channels. But it should know all of them.

![screen shot 2015-04-09 at 07 34 06](https://cloud.githubusercontent.com/assets/11651596/7061000/8993d1e8-de8b-11e4-932c-e2b24a130464.png)
![screen shot 2015-04-09 at 07 34 41](https://cloud.githubusercontent.com/assets/11651596/7061003/8bf4917a-de8b-11e4-8a64-57f022f3b0a1.png)
![screen shot 2015-04-09 at 07 35 28](https://cloud.githubusercontent.com/assets/11651596/7061004/8f997412-de8b-11e4-9113-1dd2da8f4d04.png)

**Comment by StephanPreibisch** [comment]
This will be solved by optionally splitting the bounding box definition from fusion itself. For now, just apply the transformation to all views and run the fusion again.

**Comment by StephanPreibisch** [comment]
There is now a new command:
Plugins>Multiview Reconstruction>Batch Processing>Tools, "Define Bounding Box"

It allows to define a bounding box on whatever views and detections one wants. This bounding box is remembered and saved to the XML, so you can fuse any subset of views with a bounding box that was defined on a completely different set of views.
