### ISSUE TITLE
NullPointerException defining diSPIM dataset

### ISSUE THREAD

**Issue by HannahBa** [bigdataviewer/SPIM_Registration#26]
Defining a new MicroManager diSPIM dataset

```
Using spimdata version: 0.9-revision
Using spimreconstruction version: 2.1.9
2
Investigating file 'D:\Hannah\20150401_mcf-10a_180x300_part2\MMStack.ome.tif'.
```

I get the following exception:

```
(Fiji Is Just) ImageJ 2.0.0-rc-28/1.49q; Java 1.8.0_40 [64-bit]; Windows 7 6.1; 153MB of 60000MB (<1%)
 
java.lang.NullPointerException
	at spim.fiji.spimdata.imgloaders.MultipageTiffReader.calZ(MultipageTiffReader.java:507)
	at spim.fiji.datasetmanager.MicroManager.showDialogs(MicroManager.java:276)
	at spim.fiji.datasetmanager.MicroManager.createDataset(MicroManager.java:83)
	at spim.fiji.plugin.Define_Multi_View_Dataset.defineDataset(Define_Multi_View_Dataset.java:104)
	at spim.fiji.plugin.Data_Explorer.run(Data_Explorer.java:53)
	at ij.IJ.runUserPlugIn(IJ.java:199)
	at ij.IJ.runPlugIn(IJ.java:163)
	at ij.Executer.runCommand(Executer.java:131)
	at ij.Executer.run(Executer.java:64)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by StephanPreibisch** [comment]
Hi @HannahBa,

is this a diSPIM dataset? Or OpenSPIM?

Cheers,
Stephan

**Comment by StephanPreibisch** [comment]
In any case, can you get this dataset to me ... it should not crash.

**Comment by StephanPreibisch** [comment]
You seem to be using an older version of the micromanager software where the tags are missing ... in this case there is no "z-step_um". I will ask Nico Stuurmann about this ...

**Comment by HannahBa** [comment]
Oh you're right. Would it be much hassle to adapt it such that older versions are supported as well? The calibration could be set manually... Unfortunately in our lab we are having some troubles with the most recent versions of Micro-Manager.

**Comment by nicost** [comment]
HI HannahBa,  

Can you contact me (and/or Jon) directly about the problems you are having with the latest Micro-Manager version?  It works very nicely for me here, and I'd like to see it work for you as well.

**Comment by StephanPreibisch** [comment]
Hi @HannahBa,

I fixed it so it doesn't crash, but the correct calibration cannot be read, you have to update it yourself ... thanks @nicost for helping.

Fixed with commit https://github.com/bigdataviewer/SPIM_Registration/commit/2e6c774e65c45ed073a3c7b7bd32afb1415bda87

**Comment by HannahBa** [comment]
Perfect, that's all I need for now. Thanks @StephanPreibisch and @nicost !
