### ISSUE TITLE
What is new in 2.2.0?

### ISSUE THREAD

**Issue by StephanJanosch** [bigdataviewer/SPIM_Registration#30]
no comment

**Comment by StephanPreibisch** [comment]
once I have a minute I will do a proper release on github

**Comment by ctrueden** [comment]
@StephanJanosch This is my fault; I cut a release (without asking @StephanPreibisch for permission, no less!) and did not write up the changes. Actually, with most Fiji components we never do that; @StephanPreibisch is very thorough and helpful to do that for SPIM Registration!

Anyway, the reason we needed the 2.1.10 release was to make the plugin compatible with Bio-Formats 5.1.0, to which Fiji was updated late Wednesday. If I hadn't uploaded the new version, it would have stopped working.

Thanks very much @StephanPreibisch for following up, and sorry if the timing of things has caused any awkward pressure.

**Comment by StephanPreibisch** [comment]
No worries @ctrueden ... it made us release all the hackathon stuff already, which is great :) This afternoon I should hopefully find some time to write the things down properly.

Thanks a lot for looking out for everything @ctrueden!

**Comment by StephanJanosch** [comment]
@ctrueden I can understand that you needed to upgrade. But @StephanPreibisch has such a big (multiple steps, huge amount of input parameters) plugin and we use it in strict manner (on a cluster, using beanshell calling his plugin, GPU...) so we built quite some infrastructure around it. So every time we get an update, we are wondering what will break. And if you often find some cracks in your well established pipeline, you want to be informed what is going on.

It's just the nature of our usage, which alerts us of every undocumented change.

**Comment by StephanPreibisch** [comment]
The only change that is related to cluster processing should be the documented fix of issue https://github.com/bigdataviewer/SPIM_Registration/issues/23

**Comment by ctrueden** [comment]
@StephanJanosch It is unlikely that Fiji will ever have a comprehensive "what's new" with every single new release of every single plugin. Given your usage, I would encourage you to set up a "staging" or test environment where you can vet new versions of Fiji. And do not update Fiji unless you must, to receive a bug-fix or needed enhancement.

**Comment by psteinb** [comment]
@ctrueden: this sounds like a pretty handy feature, is setting up a fiji 
staging area documented somewhere? I couldn't find something on fiji.sc

-- 
Peter Steinbach, Dr. rer. nat.
HPC Developer
Scionics Computer Innovation GmbH
Tatzberg 47-51
01307 Dresden
fon: +49 351 210 2882
fax: +49 351 210 1689
http://www.scionics.de
Sitz der Gesellschaft:  Dresden (Main office)
Amtsgericht - Registergericht:  Dresden HRB 20337 (Commercial Registry)
Ust-IdNr.:  DE813263791 (VAT ID Number)
Geschäftsführer:  John Duperon, Jeff Oegema (Managing Directors)

**Comment by ctrueden** [comment]
@psteinb I was referring more generally to the idea of a "staging" server or servers, as compared to "production" server(s). With the easy availability of VMs these days, and even containers like Docker becoming seriously popular, it is easier than ever to keep your concerns well separated. Fiji tries to help by being a portable application—you can have as many copies of Fiji installed on the file system as you want—but regardless, a proper testing environment would have its own copy of Fiji which you could update more aggressively, test, then migrate to production if everything is still working. This is the sort of job a dedicated IT person/team is supposed to handle.

**Comment by dscho** [comment]
> This is the sort of job a dedicated IT person/team is supposed to handle.

@ctrueden you do realize that @psteinb is exactly such a dedicated IT person? Just sayin'...

**Comment by ctrueden** [comment]
In that case, I'd be interested to hear any suggestions that @psteinb might have for ImageJ specifically to improve its usability in split Dev/Training/Production environments.

**Comment by StephanPreibisch** [comment]
Here are the release notes: https://github.com/bigdataviewer/SPIM_Registration/releases/tag/SPIM_Registration-2.3.1
