### ISSUE TITLE
Implement missing views in MVR plugin

### ISSUE THREAD

**Issue by APavlopoulos** [bigdataviewer/SPIM_Registration#31]

**Comment by StephanPreibisch** [comment]
Fixed with commits https://github.com/bigdataviewer/SPIM_Registration/commit/0ac6e0e4817b39df4fe4fddc94e76a9a4d73e60c and https://github.com/bigdataviewer/SPIM_Registration/commit/8d8f5d9a28d8ddbbf355b3096e1b6c12d29e179a
