### ISSUE TITLE
problem when resaving datasets with missing views into hdf5

### ISSUE THREAD

**Issue by APavlopoulos** [bigdataviewer/SPIM_Registration#35]
Please check the attached screenshot for the actual error message on the console and log windows

![screenshot](https://cloud.githubusercontent.com/assets/11996540/7333471/afaa730e-eb3e-11e4-9fe0-07dc4997c42b.jpg)

**Comment by StephanPreibisch** [comment]
Solved with commit https://github.com/bigdataviewer/SPIM_Registration/commit/945343cd9cc970aebc1d856b27c60f7823f55167 and https://github.com/bigdataviewer/SPIM_Registration/commit/d3d9063bc71529e1f40a4d0a1b6566e3054d523d
