### ISSUE TITLE
Bead segmentation: Difference-of-Mean

### ISSUE THREAD

**Issue by schmiedc** [bigdataviewer/SPIM_Registration#38]
Hi Stephan,

When using the difference of Mean bead segmentation in spimreconstruction version: 2.1.1-SNAPSHOT I was using very segmentation parameters similar to SPIM_Registration:

For example:
r1=2
r2=3
t=0.005

These parameters do not work anymore with spimreconstruction version: 2.3.1. Moreover it seems that I cannot robustly register my dataset over the whole time lapse with the same bead segmentation. 

Cheers,
Christopher

**Comment by StephanPreibisch** [comment]
@tpietzsch suggested that it is due to commit https://github.com/bigdataviewer/SPIM_Registration/commit/c19499cbb2aac09a59ec38805f702575c57211d3 and https://github.com/bigdataviewer/SPIM_Registration/commit/31ad68f2d2235467c91be4ef66ad97d64a059c84 where we now use the pre-downsampled versions from the HDF5 directly as the HDF5 downsampling is slightly different as the MultiViewReconstruction downsampling:

" The downsampling methods used by the SPIM_Registration and by the BDV export are slightly different: When downsampling by factor 2 in every axis, BDV averages a block of 2x2x2 pixels weighting with factors 0.5, 0.5 in every direction; this places the downsampled pixel location between the source pixels. SPIM_Registration places downsampled pixel locations on every other pixel, weighting 3x3x3 pixels with factors 0.25, 0.5, 0.25 in every direction."

**Comment by StephanPreibisch** [comment]
@schmiedc pointed out:
"This is a difference between spimreconstruction version: 2.3.1 and spimreconstruction version: 2.1.1-SNAPSHOT.

It also seems that everything is less robust now. I have a very hard time to register my recordings over the whole timelapse. Something which I never encountered before and I did not change my imaging setup at all."

**Comment by StephanPreibisch** [comment]
I will test if, maybe there is still a simple bug somewhere. For Difference-of-Gaussian it works, so I do not see why it should be any different for Difference-of-Mean.

**Comment by schmiedc** [comment]
Great thanks a lot!

If the parameters have changed it can be that I have not arrived at the new optimum yet. I will try more tomorrow.

**Comment by schmiedc** [comment]
I was able to process my data sets successfully using the difference-of-mean bead segmentation. 

I guess this change gives a performance boost so you should keep it. I will tell the others that they should change their parameters accordingly.

**Comment by StephanPreibisch** [comment]
Hi @schmiedc,

I have a hard time going back to version 2.1.1 as meanwhile the entire FIJI-infrastructure was changed - i.e. mpicbg was updated by @axtimwalde. Can you be a bit more precise in what changed? Can you please visualize the detections for version 2.1.1 and 2.3.1 so I can understand what is going on (is it more or less beads)?

Do you set the min/max manually?

In general, you should really use the downsampling for finding beads ... makes your life much easier.

Cheers,
Stephan

**Comment by schmiedc** [comment]
Hi @StephanPreibisch, 

Here is a screenshot showing the interactive bead detection using Difference-of-Mean detection without prior downsampling with 3-dimensional quadratic fit. The version was for the Fiji here 2.1.2: 
![2 1 2](https://cloud.githubusercontent.com/assets/10744409/7397512/4c1fb9ac-eea9-11e4-8d96-0be311e5336d.png)
Beads are detected and some detection in the sample but this would give me a ok registration. Logfile for this detection and registration you find below. 

When doing this in version 2.3.1 I get an "oversegmentation" of beads. This means I get much more detections in on a single bead. 
![2 3 1](https://cloud.githubusercontent.com/assets/10744409/7397752/d2326cbe-eeaa-11e4-89aa-32cfea117e2f.png)

I do not set the min/max manually and I think I did not touch anything there. But from the log files it seems that the min/max is different between the two versions: 

2.1.2: (Wed Apr 29 19:53:33 CEST 2015): min intensity = 151.0, max intensity = 65535.0
2.3.1: (Wed Apr 29 19:58:13 CEST 2015): min intensity = -32756.0, max intensity = 32727.0

Good, then I will incorporate that in my workflow. 

Logfile 2.1.2
---
Using spimdata version: 0.9-revision
Using spimreconstruction version: 2.1.2
angles selected: 0, 72, 144, 216, 288
channels selected: green
illuminations selected: 0
Timepoints selected: 0
(Wed Apr 29 19:53:30 CEST 2015): Requesting Img from ImgLoader (tp=0, setup=0)
(Wed Apr 29 19:53:33 CEST 2015): min intensity = 151.0, max intensity = 65535.0
(Wed Apr 29 19:53:33 CEST 2015): Computing Difference-of-Mean, diameters = (5, 7, 5, 7, 5, 7)
(Wed Apr 29 19:53:35 CEST 2015): Extracting peaks (radius=2, threshold=0.0028735597)
(Wed Apr 29 19:53:42 CEST 2015): Subpixel localization using quadratic n-dimensional fit
(Wed Apr 29 19:53:42 CEST 2015): Found 4289 peaks.
(Wed Apr 29 19:53:42 CEST 2015): Requesting Img from ImgLoader (tp=0, setup=1)
(Wed Apr 29 19:53:51 CEST 2015): min intensity = 140.0, max intensity = 65535.0
(Wed Apr 29 19:53:51 CEST 2015): Computing Difference-of-Mean, diameters = (5, 7, 5, 7, 5, 7)
(Wed Apr 29 19:53:54 CEST 2015): Extracting peaks (radius=2, threshold=0.0028735597)
(Wed Apr 29 19:54:08 CEST 2015): Subpixel localization using quadratic n-dimensional fit
(Wed Apr 29 19:54:08 CEST 2015): Found 4003 peaks.
(Wed Apr 29 19:54:08 CEST 2015): Requesting Img from ImgLoader (tp=0, setup=2)
(Wed Apr 29 19:54:17 CEST 2015): min intensity = 146.0, max intensity = 65535.0
(Wed Apr 29 19:54:17 CEST 2015): Computing Difference-of-Mean, diameters = (5, 7, 5, 7, 5, 7)
(Wed Apr 29 19:54:20 CEST 2015): Extracting peaks (radius=2, threshold=0.0028735597)
(Wed Apr 29 19:54:27 CEST 2015): Subpixel localization using quadratic n-dimensional fit
(Wed Apr 29 19:54:27 CEST 2015): Found 4275 peaks.
(Wed Apr 29 19:54:27 CEST 2015): Requesting Img from ImgLoader (tp=0, setup=3)
(Wed Apr 29 19:54:36 CEST 2015): min intensity = 148.0, max intensity = 65535.0
(Wed Apr 29 19:54:36 CEST 2015): Computing Difference-of-Mean, diameters = (5, 7, 5, 7, 5, 7)
(Wed Apr 29 19:54:39 CEST 2015): Extracting peaks (radius=2, threshold=0.0028735597)
(Wed Apr 29 19:54:49 CEST 2015): Subpixel localization using quadratic n-dimensional fit
(Wed Apr 29 19:54:49 CEST 2015): Found 4177 peaks.
(Wed Apr 29 19:54:49 CEST 2015): Requesting Img from ImgLoader (tp=0, setup=4)
(Wed Apr 29 19:54:58 CEST 2015): min intensity = 150.0, max intensity = 65535.0
(Wed Apr 29 19:54:58 CEST 2015): Computing Difference-of-Mean, diameters = (5, 7, 5, 7, 5, 7)
(Wed Apr 29 19:55:02 CEST 2015): Extracting peaks (radius=2, threshold=0.0028735597)
(Wed Apr 29 19:55:12 CEST 2015): Subpixel localization using quadratic n-dimensional fit
(Wed Apr 29 19:55:12 CEST 2015): Found 4034 peaks.
Opening of files took: 33 sec.
Detecting interest points took: 68 sec.
Creating directory: /home/schmied/Desktop/2015-04-01_LZ2_Stock46/./interestpoints
(Wed Apr 29 19:55:12 CEST 2015): Saved xml '/home/schmied/Desktop/2015-04-01_LZ2_Stock46/./dataset.xml'.
Using spimdata version: 0.9-revision
Using spimreconstruction version: 2.1.2
angles selected: 0, 72, 144, 216, 288
channels selected: green
illuminations selected: 0
Timepoints selected: 0
registering channel: 0 label: 'beads'
Registration algorithm: Fast 3d geometric hashing (rotation invariant)
Registration type: TIMEPOINTS_INDIVIDUALLY
Channels to process: 1
Following tiles are fixed:
Angle:0 Channel:green Illum:0 TimePoint:0
Following tiles are reference tiles (for mapping back if there are no fixed tiles):
(Wed Apr 29 19:55:34 CEST 2015): Starting registration
(Wed Apr 29 19:55:35 CEST 2015): [TP=0 angle=0, ch=green, illum=0 >>> TP=0 angle=288, ch=green, illum=0]: Model found but not enough remaining inliers (6/12) after RANSAC of 13
(Wed Apr 29 19:55:35 CEST 2015): [TP=0 angle=144, ch=green, illum=0 >>> TP=0 angle=288, ch=green, illum=0]: Remaining inliers after RANSAC: 29 of 38 (76%) with average error 0.6376251162126146
(Wed Apr 29 19:55:35 CEST 2015): [TP=0 angle=72, ch=green, illum=0 >>> TP=0 angle=288, ch=green, illum=0]: Model found but not enough remaining inliers (5/12) after RANSAC of 17
(Wed Apr 29 19:55:35 CEST 2015): [TP=0 angle=0, ch=green, illum=0 >>> TP=0 angle=216, ch=green, illum=0]: Model found but not enough remaining inliers (9/12) after RANSAC of 21
(Wed Apr 29 19:55:35 CEST 2015): [TP=0 angle=72, ch=green, illum=0 >>> TP=0 angle=144, ch=green, illum=0]: Remaining inliers after RANSAC: 17 of 24 (71%) with average error 0.47897201688850627
(Wed Apr 29 19:55:35 CEST 2015): [TP=0 angle=216, ch=green, illum=0 >>> TP=0 angle=288, ch=green, illum=0]: Remaining inliers after RANSAC: 19 of 32 (59%) with average error 0.8487392514944077
(Wed Apr 29 19:55:35 CEST 2015): [TP=0 angle=0, ch=green, illum=0 >>> TP=0 angle=72, ch=green, illum=0]: Remaining inliers after RANSAC: 22 of 31 (71%) with average error 0.48824133012782445
(Wed Apr 29 19:55:35 CEST 2015): [TP=0 angle=144, ch=green, illum=0 >>> TP=0 angle=216, ch=green, illum=0]: Remaining inliers after RANSAC: 24 of 39 (62%) with average error 0.6637030877172946
(Wed Apr 29 19:55:35 CEST 2015): [TP=0 angle=0, ch=green, illum=0 >>> TP=0 angle=144, ch=green, illum=0]: Remaining inliers after RANSAC: 23 of 32 (72%) with average error 0.37548553166182147
(Wed Apr 29 19:55:35 CEST 2015): [TP=0 angle=72, ch=green, illum=0 >>> TP=0 angle=216, ch=green, illum=0]: Remaining inliers after RANSAC: 53 of 60 (88%) with average error 0.45251904934082393
(Wed Apr 29 19:55:35 CEST 2015): Number of Candidates: 307
(Wed Apr 29 19:55:35 CEST 2015): Number of Inliers: 187
(Wed Apr 29 19:55:35 CEST 2015): Fixing view-tile (viewSetupId = 0)
(Wed Apr 29 19:55:35 CEST 2015): prealigned all tiles
(Wed Apr 29 19:55:35 CEST 2015): Global optimization of 5 view-tiles (Model=InterpolatedAffineModel3D):
(Wed Apr 29 19:55:35 CEST 2015):    Avg Error: 0.7497785329818726px
(Wed Apr 29 19:55:35 CEST 2015):    Min Error: 0.618316650390625px
(Wed Apr 29 19:55:35 CEST 2015):    Max Error: 0.955717146396637px
(Wed Apr 29 19:55:35 CEST 2015): Transformation Models:
ViewId=0: 1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0, Scaling: 1.0, 1.0, 1.0
ViewId=1: 0.30891624,0.003690057,-0.93296385,514.92206,0.0041410225,1.0001583,0.0056575052,-3.863286,0.95615005,-0.0064696223,0.30629897,-518.6426, Scaling: 1.0050996735949083, 0.9817288672416037, 1.0001485506422547
ViewId=2: -0.8110823,0.0104737915,-0.58256,1208.8259,0.01110992,1.0000027,0.0040557883,-13.522711,0.5880307,-0.004907895,-0.8039546,-193.64363, Scaling: 1.001890742551663, 1.0001800409269965, 0.9927173500392482
ViewId=3: -0.80787957,0.010953756,0.58219546,1084.9304,0.010084486,1.0001467,-0.003641274,-2.0031228,-0.59520674,0.0018000416,-0.8048903,580.00964, Scaling: 1.0051383208108156, 0.9917212334168966, 1.000228979506965
ViewId=4: 0.30986187,0.0043132044,0.93236023,337.73688,0.002424169,1.000144,-0.005693266,-3.585645,-0.95470905,0.004684038,0.30434018,671.6006, Scaling: 1.00380181733798, 0.980758923377764, 1.00013149781686


Logfile 2.3.1:
---
Using spimdata version: 0.9-revision
Using spimreconstruction version: 2.3.1
angles selected: 0, 72, 144, 216, 288
channels selected: green
illuminations selected: 0
Timepoints selected: 0
(Wed Apr 29 19:57:28 CEST 2015): Requesting Img from ImgLoader (tp=0, setup=0)
(Wed Apr 29 19:58:06 CEST 2015): Requesting Img from ImgLoader (tp=0, setup=0)
(Wed Apr 29 19:58:13 CEST 2015): min intensity = -32756.0, max intensity = 32727.0
(Wed Apr 29 19:58:13 CEST 2015): Computing Difference-of-Mean, diameters = (5, 7, 5, 7, 5, 7)
(Wed Apr 29 19:58:15 CEST 2015): Extracting peaks (radius=2, threshold=0.0028735597)
(Wed Apr 29 19:58:22 CEST 2015): Subpixel localization using quadratic n-dimensional fit
(Wed Apr 29 19:58:22 CEST 2015): Found 6273 peaks.
(Wed Apr 29 19:58:22 CEST 2015): Correcting coordinates for downsampling (xy=1x, z=1x) using AffineTransform: 3d-affine: (1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0)
(Wed Apr 29 19:58:22 CEST 2015): Requesting Img from ImgLoader (tp=0, setup=1)
(Wed Apr 29 19:58:28 CEST 2015): min intensity = -32761.0, max intensity = 32763.0
(Wed Apr 29 19:58:28 CEST 2015): Computing Difference-of-Mean, diameters = (5, 7, 5, 7, 5, 7)
(Wed Apr 29 19:58:32 CEST 2015): Extracting peaks (radius=2, threshold=0.0028735597)
(Wed Apr 29 19:58:37 CEST 2015): Subpixel localization using quadratic n-dimensional fit
(Wed Apr 29 19:58:38 CEST 2015): Found 6462 peaks.
(Wed Apr 29 19:58:38 CEST 2015): Correcting coordinates for downsampling (xy=1x, z=1x) using AffineTransform: 3d-affine: (1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0)
(Wed Apr 29 19:58:38 CEST 2015): Requesting Img from ImgLoader (tp=0, setup=2)
(Wed Apr 29 19:58:44 CEST 2015): min intensity = -32767.0, max intensity = 32763.0
(Wed Apr 29 19:58:44 CEST 2015): Computing Difference-of-Mean, diameters = (5, 7, 5, 7, 5, 7)
(Wed Apr 29 19:58:47 CEST 2015): Extracting peaks (radius=2, threshold=0.0028735597)
(Wed Apr 29 19:58:56 CEST 2015): Subpixel localization using quadratic n-dimensional fit
(Wed Apr 29 19:58:56 CEST 2015): Found 7473 peaks.
(Wed Apr 29 19:58:56 CEST 2015): Correcting coordinates for downsampling (xy=1x, z=1x) using AffineTransform: 3d-affine: (1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0)
(Wed Apr 29 19:58:56 CEST 2015): Requesting Img from ImgLoader (tp=0, setup=3)
(Wed Apr 29 19:59:02 CEST 2015): min intensity = -32761.0, max intensity = 32755.0
(Wed Apr 29 19:59:02 CEST 2015): Computing Difference-of-Mean, diameters = (5, 7, 5, 7, 5, 7)
(Wed Apr 29 19:59:05 CEST 2015): Extracting peaks (radius=2, threshold=0.0028735597)
(Wed Apr 29 19:59:15 CEST 2015): Subpixel localization using quadratic n-dimensional fit
(Wed Apr 29 19:59:15 CEST 2015): Found 6189 peaks.
(Wed Apr 29 19:59:15 CEST 2015): Correcting coordinates for downsampling (xy=1x, z=1x) using AffineTransform: 3d-affine: (1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0)
(Wed Apr 29 19:59:15 CEST 2015): Requesting Img from ImgLoader (tp=0, setup=4)
(Wed Apr 29 19:59:21 CEST 2015): min intensity = -32765.0, max intensity = 32759.0
(Wed Apr 29 19:59:21 CEST 2015): Computing Difference-of-Mean, diameters = (5, 7, 5, 7, 5, 7)
(Wed Apr 29 19:59:24 CEST 2015): Extracting peaks (radius=2, threshold=0.0028735597)
(Wed Apr 29 19:59:33 CEST 2015): Subpixel localization using quadratic n-dimensional fit
(Wed Apr 29 19:59:33 CEST 2015): Found 5841 peaks.
(Wed Apr 29 19:59:33 CEST 2015): Correcting coordinates for downsampling (xy=1x, z=1x) using AffineTransform: 3d-affine: (1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0)
Opening of files took: 25 sec.
Detecting interest points took: 61 sec.
registering channel: 0 label: 'beads'
Registration algorithm: Fast 3d geometric hashing (rotation invariant)
Registration type: TIMEPOINTS_INDIVIDUALLY
Channels to process: 1
Following tiles are fixed:
Angle:0 Channel:green Illum:0 TimePoint:0
Following tiles are reference tiles (for mapping back if there are no fixed tiles):
(Wed Apr 29 19:59:53 CEST 2015): Starting registration
(Wed Apr 29 19:59:53 CEST 2015): Finding correspondences for subset: individual timepoint registration: 0(id=0)
(Wed Apr 29 19:59:55 CEST 2015): [TP=0 angle=72, ch=green, illum=0 >>> TP=0 angle=144, ch=green, illum=0]: NO Model found after RANSAC of 16
(Wed Apr 29 19:59:55 CEST 2015): [TP=0 angle=72, ch=green, illum=0 >>> TP=0 angle=288, ch=green, illum=0]: NO Model found after RANSAC of 20
(Wed Apr 29 19:59:55 CEST 2015): [TP=0 angle=0, ch=green, illum=0 >>> TP=0 angle=144, ch=green, illum=0]: NO Model found after RANSAC of 19
(Wed Apr 29 19:59:55 CEST 2015): [TP=0 angle=144, ch=green, illum=0 >>> TP=0 angle=288, ch=green, illum=0]: NO Model found after RANSAC of 25
(Wed Apr 29 19:59:55 CEST 2015): [TP=0 angle=72, ch=green, illum=0 >>> TP=0 angle=216, ch=green, illum=0]: NO Model found after RANSAC of 15
(Wed Apr 29 19:59:55 CEST 2015): [TP=0 angle=216, ch=green, illum=0 >>> TP=0 angle=288, ch=green, illum=0]: Model found but not enough remaining inliers (4/12) after RANSAC of 39
(Wed Apr 29 19:59:55 CEST 2015): [TP=0 angle=0, ch=green, illum=0 >>> TP=0 angle=288, ch=green, illum=0]: NO Model found after RANSAC of 21
(Wed Apr 29 19:59:55 CEST 2015): [TP=0 angle=0, ch=green, illum=0 >>> TP=0 angle=216, ch=green, illum=0]: NO Model found after RANSAC of 33
(Wed Apr 29 19:59:55 CEST 2015): [TP=0 angle=0, ch=green, illum=0 >>> TP=0 angle=72, ch=green, illum=0]: NO Model found after RANSAC of 25
(Wed Apr 29 19:59:55 CEST 2015): [TP=0 angle=144, ch=green, illum=0 >>> TP=0 angle=216, ch=green, illum=0]: NO Model found after RANSAC of 34
(Wed Apr 29 19:59:55 CEST 2015): Number of Candidates: 247
(Wed Apr 29 19:59:55 CEST 2015): Number of Inliers: 0
(Wed Apr 29 19:59:55 CEST 2015): Fixing view-tile (viewSetupId = 0)
There are no connected tiles, cannot do an optimization. Quitting.

**Comment by StephanPreibisch** [comment]
@schmiedc, fantastic job :)

2.1.2: (Wed Apr 29 19:53:33 CEST 2015): min intensity = 151.0, max intensity = 65535.0
2.3.1: (Wed Apr 29 19:58:13 CEST 2015): min intensity = -32756.0, max intensity = 32727.0

The reason is for sure that the min/max intensity is wrong. I will investigate that later today!

**Comment by StephanPreibisch** [comment]
Can you please display the first view (Tools > Display View), does it look wrong where the highest intensities should be? I suspect this should be different between 2.1.2 and 2.3.1.

**Comment by schmiedc** [comment]
Thank you! 

When I do Tools > Display View the images look fine, no clipping of the beads. But when I look at the same beads in the interactive view when via bead segmentation there is clipping on the beads. Here a screenshot with Tools > Display View 1. 32 Bit, 16 Bit and Interactive Bead Segmentation same slice of the stack and same beads, the histogram on the right is from the Interactive view: 

![intensity](https://cloud.githubusercontent.com/assets/10744409/7398283/65ac45b6-eeae-11e4-84cd-e0857792f76e.png)

**Comment by StephanPreibisch** [comment]
OK, thanks again @schmiedc ... I will check it out, hopefully a simple bug somewhere.

**Comment by schmiedc** [comment]
BTW I love the new application! Great job also @tpietzsch!

**Comment by StephanPreibisch** [comment]
thanks a lot :)

**Comment by StephanPreibisch** [comment]
@tpietzsch: I fixed a bug in the bigdataviewer-core (https://github.com/bigdataviewer/bigdataviewer-core/tree/fixUShortAsFloat). It read the float data as short, not unsignedshort. If you like my simple fix, you could just merge the branch into master and release a new version ... thanks a lot!

If anybody needs a quick fix, I put the jar of bigdataviewer-core for upload here: http://fly.mpi-cbg.de/preibisch/bigdataviewer-core-1.1.3-SNAPSHOT.jar

**Comment by tpietzsch** [comment]
whoa... Thanks @StephanPreibisch, good catch! I merged it and I'm releasing now.

**Comment by tpietzsch** [comment]
@StephanPreibisch I released

pom-bigdataviewer 2.1.3
bigdataviewer-core 1.1.3
bigdataviewer_fiji 1.0.11

and uploaded bigdataviewer-core 1.1.3 to the Fiji update site.

**Comment by StephanPreibisch** [comment]
thanks @tpietzsch
