### ISSUE TITLE
PSF is not displayed after deconvolution (even if I selected the option)

### ISSUE THREAD

**Issue by fernandoamat** [bigdataviewer/SPIM_Registration#42]
I load a PSF from a TIFF file and "Show indicidual PSF" in PSF display drop down menu. However, when deconvolution is done, no PSF is displayed in Fiji.

**Comment by StephanPreibisch** [comment]
Hi @fernandoamat - Oh yes, it will only display the PSF's it if you extract it from the beads. Mmh, why would you want to display your TIFFs, do I miss something?

**Comment by fernandoamat** [comment]
I want to see how the PSF looks when it has been transformed, so I can make sure I input it correctly (it is kind of a sanity check). Another usage is in combination with the option "No fusion. Output each transformed view separately". I can store in hard disk both the PSF and the images transformed (so they are all registered to each other) and easily test different deconvolution and fusion algorithms without having to worry about registration any more.

**Comment by fernandoamat** [comment]
I guess another option (with the explorer dialogs) would be to be able to apply a set of transformations to any open image in ImageJ.

**Comment by StephanPreibisch** [comment]
Ah, I see, that makes sense :) Fixed with commit https://github.com/bigdataviewer/SPIM_Registration/commit/eaa1cefc3cffef02fe7632c5612e84e1223c18df - I will send you a JAR to test tonight!
