### ISSUE TITLE
Macro input was changed

### ISSUE THREAD

**Issue by schmiedc** [bigdataviewer/SPIM_Registration#43]
bounding_box=[Define manually] changed to bounding_box=[Define Manually] in the most recent version. 

A little Easter egg for me ;) 
I decided to report this although it is not a big issue but took some time to determine.
Please stay consistent with cases over the versions. 

Thank you!

**Comment by StephanPreibisch** [comment]
I am really really sorry about that, I did not even realize that. But please understand, this can happen during a major change, as it was here introducing the Predefined Bounding Box that is also saved to the XML. There is no compiler that will tell you that, and macro recording still worked. But thanks for reporting, I changed it back to the original version https://github.com/bigdataviewer/SPIM_Registration/commit/1c847096158b6a6a97bdf125dd80314b79104fee

**Comment by schmiedc** [comment]
No problem! Thank you!

**Comment by psteinb** [comment]
Hi -
(thinking out loud) maybe one could help this situation: I was thinking 
of something along the lines of the flyweight pattern 
(http://en.wikipedia.org/wiki/Flyweight_pattern#Example_in_Java). So, 
let's assume that every configuration option would be a class with a 
constructor from string and a toString method (see the CoffeeFlavour 
class on the wikipedia page above). As there are a myriad of options in 
SPIM_Registration by now, there would be many of those classes (the 
source code could be generated by an outside tool even). in any case, 
SPIM_Registration would need a factory to register and check options 
that are given through a simple string. Maybe this is already supported 
in the ImgLibX/ImageJ world?
In any case, what would be the advantage? you could retain using macros, 
but an error/exception would be thrown upon calling the plugin if the 
options given are invalid or not. This would prevent having these kind 
of problems in the future and would help users find bugs earlier.

**Comment by StephanPreibisch** [comment]
Hi @psteinb,

I agree that it has to change and this looks like a good option. Right now, I unfortunately have no time as I hardly cope up with adding/fixing features next to doing experiments and other projects. This will, however, change once I start my own lab in Berlin later this year.

Thanks a lot for the input,
Stephan
