### ISSUE TITLE
Deconvolution .tif

### ISSUE THREAD

**Issue by schmiedc** [bigdataviewer/SPIM_Registration#46]
Hi Stephan,

Currently the plugin on the cluster cannot append fused or deconvolved data to an existing hdf5 dataset. Which I can work around for the fused data by creating a new hdf5 dataset. 

However the deconvolved data I cannot even put into a new hdf5 project without putting it into 16Bit before. Which is tedious. It would be great if that would be integrated that I can at least make a new dataset with the output of the deconvolution.

Thanks a lot!

Cheers,
Christopher

**Comment by StephanPreibisch** [comment]
Hi @schmiedc,

the HDF5 does not support 32bit yet, @tpietzsch is working on that. However, the Resave as HDF5 does support 32bit since quite some time already, it does convert it for you. If there is a bug please let me know, works for me.

Cheers,
Stephan

**Comment by StephanPreibisch** [comment]
Well, it does support it since 12 days :)

https://github.com/bigdataviewer/SPIM_Registration/commit/d0d1a3a8d4eda4617c6977165856da77bac69f7f

**Comment by schmiedc** [comment]
Hi Stephan,

:D time is relative ;) 

Here is what I see when I define a dataset on 32bit deconvolution output using the ImageJ Opener using ArrayImg and then resaving as hdf5 via the application:

![hdf5_resave_problem1_imagej](https://cloud.githubusercontent.com/assets/10744409/7543875/678b4cd0-f5c8-11e4-99d1-d3826a8d91e8.png)

Then with the LOCI opener same settings I see nothing at all: 

![hdf5_resave_problem2_loci](https://cloud.githubusercontent.com/assets/10744409/7543897/9b3b947c-f5c8-11e4-857a-8e5e9d8ec03c.png)

Using CellImg and ImageJ opener: 

![resave_hdf5_problem3_cellimg](https://cloud.githubusercontent.com/assets/10744409/7543900/a9d694f0-f5c8-11e4-972d-751ae9d48887.png)

But when I resave the data as 16Bit (to show you I am not using tricks): 

![hdf5_resave_problem2_16bit_imagej](https://cloud.githubusercontent.com/assets/10744409/7543910/be75ffa4-f5c8-11e4-84ec-a9b000b8f3a3.png)

You can download a file here if necessary (475MB):
http://www.mpi-cbg.de/~schmied/TP4_Ch0_Ill0_Ang1,2,3,4,5.tif.zip 

Cheers,
Christopher

**Comment by StephanPreibisch** [comment]
That sure looks like a bug ... on it :)

**Comment by StephanPreibisch** [comment]
It did not ask you for scaling etc right?

**Comment by schmiedc** [comment]
I checked again, no. There are also no new options as far as I see. 

Cheers,
Christopher

**Comment by StephanPreibisch** [comment]
Previously, I only fixed it for the export into HDF5, not in general for opening 32bit files. Now, the ImageJ stack loader is capable of opening 32bit images as 16bit. The first time it encounters this problem, it will ask how to scale the images right. So, it should work now ...
https://github.com/bigdataviewer/SPIM_Registration/commit/52e975f73f97d2cc18201fe9c82431379853f4c6

**Comment by StephanPreibisch** [comment]
Can you please try with the JAR from here: http://jenkins.imagej.net/view/BigDataViewer/job/SPIM_Registration/
?

**Comment by schmiedc** [comment]
Tested and works! Thanks a lot!
