### ISSUE TITLE
Dual Channel Deconvolution PSF options gone

### ISSUE THREAD

**Issue by schmiedc** [bigdataviewer/SPIM_Registration#53]
Hi Stephan, 

In a previous version (minimum 2.1.2) there was the option to select from which channel to take the PSFs. In the macro this would look like this:
"detections_to_extract_psf_for_channel_1=[Same PSF as channel 1]"
"detections_to_extract_psf_for_channel_1=beads"
In version 2.3.8 this option is gone or locally not visible anymore, together with the window to select the size of the PSFs. The program directly goes into deconvolution for CPU processing or in the GPU settings for GPU processing. Do I select something wrong?

Could you please also explain what the best way is to provide the PSFs via a file? 
Where would I get the file from? What format does the file need to be?

Thanks a lot!

Cheers,
Christopher

**Comment by StephanPreibisch** [comment]
Hi @schmiedc, could please email me the xml + zipped interestpoints (for both issues it's the same I suppose?) ... it is very hard to debug without that in this case. Thanks a lot!

**Comment by schmiedc** [comment]
Hi @StephanPreibisch  sure! Done. Correct I used the same dataset for both issues.

**Comment by StephanPreibisch** [comment]
Should be fixed with commit https://github.com/bigdataviewer/SPIM_Registration/commit/83b2373f8084ec9db46ddc63fc4ed37c44075c5f

Can you try this snapshot jar to verify? http://jenkins.imagej.net/view/BigDataViewer/job/SPIM_Registration/

**Comment by schmiedc** [comment]
Tested both and both work! Thanks a lot!
