### ISSUE TITLE
Exception DualChannel Multiview Deconvolution

### ISSUE THREAD

**Issue by schmiedc** [bigdataviewer/SPIM_Registration#54]
Hi Stephan,

I get an exception using deconvolution with dual channel. 1 channel contains the beads.
The 1st time point and the channel that contains the beads (Channel1) gets made successfully. The channel (Channel 0) without beads however not. 

I will send you the xml file and the interest points. 

Cheers
Christopher

Exception:
---

(Fiji Is Just) ImageJ 2.0.0-rc-30/1.49s; Java 1.6.0_24 [64-bit]; Linux 2.6.32-431.5.1.el6.x86_64; 7842MB of 124962MB (6%)
 
java.lang.NullPointerException
	at mpicbg.imglib.wrapper.ImgLib2.wrapFloatToImgLib1(ImgLib2.java:63)
	at mpicbg.spim.postprocessing.deconvolution2.LRFFT.wrap(LRFFT.java:83)
	at mpicbg.spim.postprocessing.deconvolution2.LRFFT.<init>(LRFFT.java:61)
	at spim.process.fusion.deconvolution.EfficientBayesianBased.fuseData(EfficientBayesianBased.java:206)
	at spim.fiji.plugin.Image_Fusion.fuse(Image_Fusion.java:173)
	at spim.fiji.plugin.Image_Fusion.run(Image_Fusion.java:76)
	at ij.IJ.runUserPlugIn(IJ.java:199)
	at ij.IJ.runPlugIn(IJ.java:163)
	at ij.Executer.runCommand(Executer.java:131)
	at ij.Executer.run(Executer.java:64)
	at java.lang.Thread.run(Thread.java:662)

Log file 
---

Using spimdata version: 0.9-revision
Using spimreconstruction version: 2.3.9-SNAPSHOT
angles selected: 0, 1, 2, 3, 4
channels selected: 0, 1
illuminations selected: 0
Timepoints selected: 0, 1
Fri May 29 13:26:12 CEST 2015: Estimating Bounding Box for Fusion. If size of images is not known (they were never opened before), some of them need to be opened once to determine their size.
(Fri May 29 13:26:20 CEST 2015): Reserving memory for fused image.
(Fri May 29 13:26:20 CEST 2015): Requesting Img from ImgLoader (tp=0, setup=0)
(Fri May 29 13:26:25 CEST 2015): Requesting Img from ImgLoader (tp=0, setup=1)
(Fri May 29 13:26:31 CEST 2015): Requesting Img from ImgLoader (tp=0, setup=2)
(Fri May 29 13:26:36 CEST 2015): Requesting Img from ImgLoader (tp=0, setup=3)
(Fri May 29 13:26:42 CEST 2015): Requesting Img from ImgLoader (tp=0, setup=4)
(Fri May 29 13:26:47 CEST 2015): Starting fusion process.
(Fri May 29 13:26:48 CEST 2015): Reserving memory for fused image.
(Fri May 29 13:26:48 CEST 2015): Requesting Img from ImgLoader (tp=0, setup=5)
(Fri May 29 13:26:52 CEST 2015): Requesting Img from ImgLoader (tp=0, setup=6)
(Fri May 29 13:26:57 CEST 2015): Requesting Img from ImgLoader (tp=0, setup=7)
(Fri May 29 13:27:02 CEST 2015): Requesting Img from ImgLoader (tp=0, setup=8)
(Fri May 29 13:27:07 CEST 2015): Requesting Img from ImgLoader (tp=0, setup=9)
(Fri May 29 13:27:12 CEST 2015): Starting fusion process.
(Fri May 29 13:27:13 CEST 2015): Reserving memory for fused image.
(Fri May 29 13:27:13 CEST 2015): Requesting Img from ImgLoader (tp=1, setup=0)
(Fri May 29 13:27:18 CEST 2015): Requesting Img from ImgLoader (tp=1, setup=1)
(Fri May 29 13:27:25 CEST 2015): Requesting Img from ImgLoader (tp=1, setup=2)
(Fri May 29 13:27:30 CEST 2015): Requesting Img from ImgLoader (tp=1, setup=3)
(Fri May 29 13:27:34 CEST 2015): Requesting Img from ImgLoader (tp=1, setup=4)
(Fri May 29 13:27:38 CEST 2015): Starting fusion process.
(Fri May 29 13:27:39 CEST 2015): Reserving memory for fused image.
(Fri May 29 13:27:39 CEST 2015): Requesting Img from ImgLoader (tp=1, setup=5)
(Fri May 29 13:27:44 CEST 2015): Requesting Img from ImgLoader (tp=1, setup=6)
(Fri May 29 13:27:48 CEST 2015): Requesting Img from ImgLoader (tp=1, setup=7)
(Fri May 29 13:27:52 CEST 2015): Requesting Img from ImgLoader (tp=1, setup=8)
(Fri May 29 13:27:56 CEST 2015): Requesting Img from ImgLoader (tp=1, setup=9)
(Fri May 29 13:28:01 CEST 2015): Starting fusion process.
(Fri May 29 13:28:02 CEST 2015): Fusion finished.
Using spimdata version: 0.9-revision
Using spimreconstruction version: 2.3.9-SNAPSHOT
angles selected: 0, 1, 2, 3, 4
channels selected: 0, 1
illuminations selected: 0
Timepoints selected: 0, 1
Fri May 29 13:28:56 CEST 2015: Estimating Bounding Box for Fusion. If size of images is not known (they were never opened before), some of them need to be opened once to determine their size.
Looking for native libraries ending with '.so', '.lib' in directory: '/home/schmied/Desktop/2015-05-29_Fiji(2.3.9-SNAP).app.cuda/lib' ... 
Trying to load following library: /home/schmied/Desktop/2015-05-29_Fiji(2.3.9-SNAP).app.cuda/lib/libFourierConvolutionCUDALib.so
Using an outdated version of the CUDA libs, cannot query free memory. Assuming total memory.
Using an outdated version of the CUDA libs, cannot query free memory. Assuming total memory.
Using device Quadro 4000 (id=0, mem=2047MB (2047MB free), CUDA capability 2.0)
Using device Quadro 4000 (id=1, mem=2047MB (2047MB free), CUDA capability 2.0)
beads --- channel: 1 angle: 0 illum: 0 timepoint: 0: 727 correspondences.
beads --- channel: 1 angle: 1 illum: 0 timepoint: 0: 667 correspondences.
beads --- channel: 1 angle: 2 illum: 0 timepoint: 0: 871 correspondences.
beads --- channel: 1 angle: 3 illum: 0 timepoint: 0: 729 correspondences.
beads --- channel: 1 angle: 4 illum: 0 timepoint: 0: 779 correspondences.
beads --- channel: 1 angle: 0 illum: 0 timepoint: 1: 731 correspondences.
beads --- channel: 1 angle: 1 illum: 0 timepoint: 1: 653 correspondences.
beads --- channel: 1 angle: 2 illum: 0 timepoint: 1: 860 correspondences.
beads --- channel: 1 angle: 3 illum: 0 timepoint: 1: 717 correspondences.
beads --- channel: 1 angle: 4 illum: 0 timepoint: 1: 812 correspondences.

Found 0 label(s) with correspondences for channel 0: 

Found 1 label(s) with correspondences for channel 1: 
Label 'beads' (channel 1) has 10/10 views with corresponding detections.
Channel 0: uses same PSF as channel 1
Channel 1: extract PSF from label 'beads'
Fusing view 0 of 4
(Fri May 29 13:29:49 CEST 2015): Reserving memory for fused & weight image.
Extracting PSF for viewsetup 5 using label 'beads' (474 corresponding detections available)
PSF size: (19, 19, 25)
Fusing view 1 of 4
(Fri May 29 13:30:14 CEST 2015): Reserving memory for fused & weight image.
Extracting PSF for viewsetup 6 using label 'beads' (404 corresponding detections available)
PSF size: (19, 19, 25)
Fusing view 2 of 4
(Fri May 29 13:30:39 CEST 2015): Reserving memory for fused & weight image.
Extracting PSF for viewsetup 7 using label 'beads' (529 corresponding detections available)
PSF size: (19, 19, 25)
Fusing view 3 of 4
(Fri May 29 13:31:05 CEST 2015): Reserving memory for fused & weight image.
Extracting PSF for viewsetup 8 using label 'beads' (477 corresponding detections available)
PSF size: (19, 19, 25)
Fusing view 4 of 4
(Fri May 29 13:31:32 CEST 2015): Reserving memory for fused & weight image.
Extracting PSF for viewsetup 9 using label 'beads' (468 corresponding detections available)
PSF size: (19, 19, 25)
Minimal number of overlapping views: 0, using 1
Average number of overlapping views: 2.539770276690097, using 2.539770276690097
Type of iteration: OPTIMIZATION_I
Number iterations: 10
OSEM speedup: 1.0
Using blocks: true
Block size: (256, 256, 256)
Using CUDA: true
Blending border: 9x9x5
Blending range: 25x25x25
PSF size (extracting): 19x19x25
Channel 0 uses same PSF as channel '1'. 
Channel 1 extracts from label 'beads'. 
ImgLib container (deconvolved): ArrayImgFactory
Using Tikhonov regularization (lambda = 0.0060)
maxSize: (63, 11, 63)
Number of blocks: 24
Number of blocks: 24
Number of blocks: 24
Number of blocks: 24
Number of blocks: 24
Fri May 29 13:32:03 CEST 2015: numThreads = 24
Fri May 29 13:32:18 CEST 2015: done normalizing.
Min number of overlapping views: 1
Average number of overlapping views: 2.593306022741662
Average intensity in overlapping area: 0.0029975544
OSEM acceleration: 1.0
Deconvolved image container: ArrayContainerFactory
iteration: 0 (Fri May 29 13:32:20 CEST 2015)
iteration: 0 --- sum change: 119824.38779413141 --- max change per pixel: 4.4350481033325195
iteration: 1 (Fri May 29 13:32:52 CEST 2015)
iteration: 1 --- sum change: 37834.8018238715 --- max change per pixel: 5.253229141235352
iteration: 2 (Fri May 29 13:33:24 CEST 2015)
iteration: 2 --- sum change: 15678.437912661233 --- max change per pixel: 3.511646270751953
iteration: 3 (Fri May 29 13:33:55 CEST 2015)
iteration: 3 --- sum change: 9907.13806076214 --- max change per pixel: 2.482752799987793
iteration: 4 (Fri May 29 13:34:26 CEST 2015)
iteration: 4 --- sum change: 7959.7276595482035 --- max change per pixel: 1.900740623474121
iteration: 5 (Fri May 29 13:34:57 CEST 2015)
iteration: 5 --- sum change: 6902.634071748602 --- max change per pixel: 1.5311756134033203
iteration: 6 (Fri May 29 13:35:28 CEST 2015)
iteration: 6 --- sum change: 6197.028420455368 --- max change per pixel: 1.2675895690917969
iteration: 7 (Fri May 29 13:35:58 CEST 2015)
iteration: 7 --- sum change: 5683.947972657719 --- max change per pixel: 1.0649070739746094
iteration: 8 (Fri May 29 13:36:30 CEST 2015)
iteration: 8 --- sum change: 5290.334145328299 --- max change per pixel: 0.9026699066162109
iteration: 9 (Fri May 29 13:37:01 CEST 2015)
iteration: 9 --- sum change: 4976.176993982874 --- max change per pixel: 0.7701091766357422
DONE (Fri May 29 13:37:31 CEST 2015).
Fri May 29 13:37:37 CEST 2015: Saving file /home/schmied/Desktop/Test_Pipeline_3.0/Dual_Channel/czi/TP0_Ch1_Ill0_Ang0,1,2,3,4.tif
Fusing view 0 of 4
(Fri May 29 13:37:38 CEST 2015): Reserving memory for fused & weight image.
Fusing view 1 of 4
(Fri May 29 13:38:00 CEST 2015): Reserving memory for fused & weight image.
Fusing view 2 of 4
(Fri May 29 13:38:24 CEST 2015): Reserving memory for fused & weight image.
Fusing view 3 of 4
(Fri May 29 13:38:47 CEST 2015): Reserving memory for fused & weight image.
Fusing view 4 of 4
(Fri May 29 13:39:12 CEST 2015): Reserving memory for fused & weight image.
Minimal number of overlapping views: 0, using 1
Average number of overlapping views: 2.539770276690097, using 2.539770276690097
Type of iteration: OPTIMIZATION_I
Number iterations: 10
OSEM speedup: 1.0
Using blocks: true
Block size: (256, 256, 256)
Using CUDA: true
Blending border: 9x9x5
Blending range: 25x25x25
PSF size (extracting): 19x19x25
Channel 0 uses same PSF as channel '1'. 
Channel 1 extracts from label 'beads'. 
ImgLib container (deconvolved): ArrayImgFactory
Using Tikhonov regularization (lambda = 0.0060)

**Comment by StephanPreibisch** [comment]
I think I see the problem ... I am on it when I find a minute, I am a little pre-occupied moving out of my apartment

**Comment by StephanPreibisch** [comment]
Fixed with commit https://github.com/bigdataviewer/SPIM_Registration/commit/14393ad2b34c5b6545921d4702285f1827ce8ada
