### ISSUE TITLE
NullPointerException  in Interest Point Registration

### ISSUE THREAD

**Issue by emmenlau** [bigdataviewer/SPIM_Registration#75]
Using v2.4.0 I fail to register interest points. I have had no success before, so I can not say which parameters are relevant. I used basically all default settings. Find the Console log here: http://data.marssoft.de/Console.txt.gz

**Comment by emmenlau** [comment]
With the same workflow, I can reproduce the error message on another dataset, so it seems to be "real". Registration crashes instantly and does not work.

**Comment by StephanPreibisch** [comment]
Hi, the log would be very helpful to understand the problem ...

**Comment by emmenlau** [comment]
Sorry for the delay! Here is the log: http://data.marssoft.de/zebrafish_beads0.5_4views-Log.zip
PS: can github attach files?

**Comment by psteinb** [comment]
for large files, maybe this is an option?
https://git-lfs.github.com/

**Comment by emmenlau** [comment]
Hey, is there an update on this? The NullPointerException blocks for me all progress :-(

**Comment by emmenlau** [comment]
Its already fixed (or not reproducible) in latest GIT trunk. Thanks :-)
