### ISSUE TITLE
First saving of XML prints errors in the log, but the error seems wrong?

### ISSUE THREAD

**Issue by emmenlau** [bigdataviewer/SPIM_Registration#77]
I have created a new dataset, re-saved as HDF5, detected interest points, and tried to register the interest points. Then I clicked "save" of the XML the first time, and received the following errors on the Console window about files missing. However what is strange: when I check for the files, they do exist. I copied one full path to a terminal and listed a file, and it is present.
Subsequent saves seems to work ok (or at least there is no more error printed).

```
InterestPointList.loadCorrespondingInterestPoints(): java.io.FileNotFoundException: D:\UserTemp\MarioEmmenlauer\zebrafish_beads0.5_4views\interestpoints\tpId_0_viewSetupId_1.beads.corr.txt (The system cannot find the file specified)
InterestPointList.loadCorrespondingInterestPoints(): java.io.FileNotFoundException: D:\UserTemp\MarioEmmenlauer\zebrafish_beads0.5_4views\interestpoints\tpId_0_viewSetupId_2.beads.corr.txt (The system cannot find the file specified)
InterestPointList.loadCorrespondingInterestPoints(): java.io.FileNotFoundException: D:\UserTemp\MarioEmmenlauer\zebrafish_beads0.5_4views\interestpoints\tpId_0_viewSetupId_3.beads.corr.txt (The system cannot find the file specified)
InterestPointList.loadCorrespondingInterestPoints(): java.io.FileNotFoundException: D:\UserTemp\MarioEmmenlauer\zebrafish_beads0.5_4views\interestpoints\tpId_0_viewSetupId_5.beads.corr.txt (The system cannot find the file specified)
InterestPointList.loadCorrespondingInterestPoints(): java.io.FileNotFoundException: D:\UserTemp\MarioEmmenlauer\zebrafish_beads0.5_4views\interestpoints\tpId_0_viewSetupId_6.beads.corr.txt (The system cannot find the file specified)
InterestPointList.loadCorrespondingInterestPoints(): java.io.FileNotFoundException: D:\UserTemp\MarioEmmenlauer\zebrafish_beads0.5_4views\interestpoints\tpId_0_viewSetupId_7.beads.corr.txt (The system cannot find the file specified)
```

**Comment by emmenlau** [comment]
With the same workflow, I can reproduce the error message on another dataset, so it seems to be "real". I do not know if it actually is a problem, or just a confusing message.

**Comment by StephanPreibisch** [comment]
It is not a problem. It is ambiguous if a) never anything was matched or b) if the file was deleted. So it tries to load to see if something is there and fails in case the registration was never run before - because the filename is defined when the interest points are detected, so to find out if there corresponding points I try to load and if it fails the list initialised with no entries.

**Comment by emmenlau** [comment]
Ok, now I understand, sorry for the confusion. Since it worked on subsequent saves, I almost assumed what you now confirmed!
